# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# .github/workflows/maven.yml
# .github/workflows/ci.yml
name: Java CI with Maven

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      sqlserver:
        image: mcr.microsoft.com/mssql/server:2019-latest
        env:
          ACCEPT_EULA: "Y"
          SA_PASSWORD: "StrongP@ssw0rd123"
        ports:
          - 1433:1433

    env:
      SPRING_DATASOURCE_URL:       jdbc:sqlserver://localhost:1433;databaseName=SME_DB;encrypt=true;trustServerCertificate=true
      SPRING_DATASOURCE_USERNAME:  sa
      SPRING_DATASOURCE_PASSWORD:  StrongP@ssw0rd123
      SPRING_JPA_HIBERNATE_DDL_AUTO: update

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: maven

      - name: Install SQL Server Tools (sqlcmd)
        run: |
          sudo apt-get update
          sudo apt-get install -y curl apt-transport-https gnupg2 lsb-release
          # Import the Microsoft GPG key
          curl -s https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -
          # Add the Microsoft package repository
          curl -s https://packages.microsoft.com/config/ubuntu/$(lsb_release -rs)/prod.list \
            | sudo tee /etc/apt/sources.list.d/msprod.list
          # Update package lists and install the required packages
          sudo apt-get update
          sudo ACCEPT_EULA=Y apt-get install -y msodbcsql17 mssql-tools unixodbc-dev
          # Update PATH for this step and subsequent steps
          echo "PATH=/opt/mssql-tools/bin:\$PATH" >> $GITHUB_ENV
          export PATH=/opt/mssql-tools/bin:$PATH

      - name: Verify sqlcmd installation
        run: |
          which sqlcmd
          sqlcmd -?

      - name: Wait for SQL Server to start (up to ~2.5 minutes)
        run: |
          echo "⏳ Waiting for SQL Server to accept connections..."
          for i in {1..30}; do
            if nc -z localhost 1433; then
              echo "✅ SQL Server is up on port 1433"
              break
            fi
            echo "  attempt $i/30: retrying in 5s..."
            sleep 5
          done

      - name: Create SME_DB database
        run: |
          echo "IF DB_ID('SME_DB') IS NULL CREATE DATABASE SME_DB;" \
            | sqlcmd -S localhost -U sa -P "$SPRING_DATASOURCE_PASSWORD"

      - name: Build & run tests
        run: mvn clean verify --batch-mode -Dspring.profiles.active=dev